<?php defined( 'ABSPATH' ) || exit; get_header(); ?>
<main id="main">
<section class="hero shell" aria-labelledby="hero-title">
<div class="hero-copy"><p class="eyebrow"><span class="brand-marker"><?php echo iamgsbala_icon(); ?></span> <?php esc_html_e( 'Independent thinking. Thoughtful development.', 'iamgsbala' ); ?></p>
<h1 id="hero-title"><?php echo esc_html( get_theme_mod( 'iamgsbala_headline', 'Built for your business. Made to work.' ) ); ?></h1>
<p class="hero-intro"><?php echo esc_html( get_theme_mod( 'iamgsbala_intro', 'I’m Balamurugan, a senior WordPress & WooCommerce full-stack developer. I turn complex requirements into thoughtful websites, custom plugins and dependable commerce experiences.' ) ); ?></p>
<div class="hero-actions"><a class="button" href="#contact"><?php esc_html_e( 'Let’s build something', 'iamgsbala' ); ?> <span aria-hidden="true">↗</span></a><a class="button button-secondary" href="#work"><?php esc_html_e( 'Explore my work', 'iamgsbala' ); ?> <span aria-hidden="true">↓</span></a></div>
<div class="hero-note"><span class="note-line"></span><?php esc_html_e( '11+ years connecting good ideas with working code.', 'iamgsbala' ); ?></div></div>
<div class="hero-art" role="img" aria-label="<?php esc_attr_e( 'Custom development connects websites, commerce and integrations', 'iamgsbala' ); ?>"><div class="art-grid"></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-center"><span class="code-mark">&lt;/&gt;</span><span>IDEA → IMPLEMENTATION</span></div><div class="art-label label-top"><span class="label-icon">W</span>WordPress</div><div class="art-label label-right"><span class="label-icon">↗</span>Commerce</div><div class="art-label label-bottom"><span class="label-icon">{ }</span>Custom code</div><div class="art-note"><span>01 / BUILD WITH PURPOSE</span><strong>Details matter.<br>So does the outcome.</strong></div><span class="art-signature"><?php echo iamgsbala_icon( 'check' ); ?></span></div>
</section>
<div class="specialties"><div class="shell specialties-inner"><span>WORDPRESS</span><i class="specialty-dot" aria-hidden="true"></i><span>WOOCOMMERCE</span><i class="specialty-dot" aria-hidden="true"></i><span>CUSTOM PLUGINS</span><i class="specialty-dot" aria-hidden="true"></i><span>API INTEGRATIONS</span><i class="specialty-dot" aria-hidden="true"></i><span>PERFORMANCE</span></div></div>
<section class="section shell" id="expertise"><div class="section-heading"><div><p class="eyebrow">01 / EXPERTISE</p><h2>Beyond the template.<br>Into the details.</h2></div><p>When your website needs to do more, I work through the business logic, integrations and small details that make it useful.</p></div>
<div class="services">
<?php $services = array(
array( '01', 'Websites & custom themes', 'From design to a working WordPress experience. Custom themes, Gutenberg blocks, ACF-powered content and responsive interfaces built around your requirements.', 'WORDPRESS · GUTENBERG · ACF' ),
array( '02', 'Commerce that fits', 'WooCommerce checkout, product and order workflows tailored to the way you sell. Payment gateways, shipping rules and complex store troubleshooting.', 'WOOCOMMERCE · PAYMENTS · SHOPIFY' ),
array( '03', 'Plugins & integrations', 'Purpose-built plugins and connections between systems. REST APIs, webhooks, cloud files and custom admin tools that bring your workflow together.', 'PHP · JAVASCRIPT · REST API' ),
array( '04', 'Performance & care', 'Investigate what’s slowing things down, resolve conflicts and keep releases considered. Technical SEO, staging, migrations and ongoing maintenance.', 'CORE WEB VITALS · DEBUGGING · DEPLOYMENT' ),
); foreach ( $services as $service ) : ?><article class="service"><div class="service-top"><span><?php echo esc_html( $service[0] ); ?></span><span aria-hidden="true">↗</span></div><h3><?php echo esc_html( $service[1] ); ?></h3><p><?php echo esc_html( $service[2] ); ?></p><div class="service-tags"><?php echo esc_html( $service[3] ); ?></div></article><?php endforeach; ?>
</div></section>
<?php get_template_part( 'template-parts/products' ); ?>
<section class="section shell about" id="about"><div><p class="eyebrow">03 / THE PERSON BEHIND THE CODE</p><h2>A developer who sees<br>the whole picture.</h2><div class="experience"><strong>11<span>+</span></strong><p>years of hands-on<br>development experience</p></div></div><div class="about-copy"><p class="large-copy">I’m <?php echo esc_html( get_theme_mod( 'iamgsbala_name', 'Balamurugan G.' ) ); ?>. My focus is turning real business requirements into websites and systems that work together.</p><p>My work spans custom WordPress builds, WooCommerce business logic, PHP and JavaScript development, payment integrations and production support. I’m comfortable moving between a frontend detail, a difficult checkout issue and the API behind it.</p><p>That broader view carries through to deployment and handover: considering performance, access, forms, payments and maintenance alongside the build itself.</p><div class="stack"><span>PHP</span><span>JavaScript</span><span>MySQL</span><span>React</span><span>REST APIs</span><span>Git</span><span>Shopify Liquid</span></div></div></section>
<section class="section shell" id="approach"><div class="section-heading"><div><p class="eyebrow">04 / HOW I WORK</p><h2>Clarity first.<br>Care through to launch.</h2></div></div><div class="process"><article><span>01 — UNDERSTAND</span><h3>Start with the real problem.</h3><p>Understand your goals, existing systems and constraints before choosing the implementation.</p></article><article><span>02 — BUILD & REFINE</span><h3>Make the details work.</h3><p>Develop in staging, connect the necessary systems and review the experience across devices.</p></article><article><span>03 — TEST & HAND OVER</span><h3>Finish with confidence.</h3><p>Check the critical workflows, plan deployment and provide a clear handover for what comes next.</p></article></div></section>
<?php get_template_part( 'template-parts/contact' ); ?>
</main><?php get_footer(); ?>
