<?php
/**
 * Template Name: OrderCraft Studio landing page
 *
 * @package iamgsbala
 */
defined( 'ABSPATH' ) || exit;
get_header( 'ordercraft' );
$plugin_url = defined( 'ORDERCRAFT_URL' ) ? ORDERCRAFT_URL : home_url( '/wp-content/plugins/ordercraft-studio-for-woocommerce/' );
?>
<main id="main" class="ordercraft-site-page ordercraft-product-page">
	<section class="ordercraft-product-hero shell">
		<div class="ordercraft-product-hero__copy">
			<p class="ordercraft-kicker"><span class="ordercraft-kicker-dot"></span><?php esc_html_e( 'Free WooCommerce plugin · by iamgsbala', 'iamgsbala' ); ?></p>
			<h1><?php esc_html_e( 'Custom orders, moving from brief to production.', 'iamgsbala' ); ?></h1>
			<p class="ordercraft-lead"><?php esc_html_e( 'OrderCraft Studio gives WooCommerce stores one clear place to collect specifications, receive artwork, send proofs, capture approval and hand work into production.', 'iamgsbala' ); ?></p>
			<div class="ordercraft-hero-actions"><a class="ordercraft-button ordercraft-button--primary" href="https://wordpress.org/plugins/ordercraft-studio-for-woocommerce/" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Get the free plugin', 'iamgsbala' ); ?> <span aria-hidden="true">↗</span></a><a class="ordercraft-button ordercraft-button--quiet" href="<?php echo esc_url( iamgsbala_ordercraft_url( 'ordercraft-documentation' ) ); ?>"><?php esc_html_e( 'Read the documentation', 'iamgsbala' ); ?> <span aria-hidden="true">↓</span></a></div>
			<p class="ordercraft-hero-note"><span></span><?php esc_html_e( 'Built for print, apparel, signage, custom products and made-to-order teams.', 'iamgsbala' ); ?></p>
		</div>
		<div class="ordercraft-product-hero__visual"><img src="<?php echo esc_url( $plugin_url . 'assets/images/icon-256x256.png' ); ?>" alt="OrderCraft Studio by iamgsbala" width="256" height="256"><div class="ordercraft-hero-orbit ordercraft-hero-orbit--one"></div><div class="ordercraft-hero-orbit ordercraft-hero-orbit--two"></div><span class="ordercraft-visual-label ordercraft-visual-label--top">SPEC → ARTWORK</span><span class="ordercraft-visual-label ordercraft-visual-label--bottom">PROOF → APPROVAL → PRODUCTION</span></div>
	</section>

	<section class="ordercraft-workflow-strip"><div class="shell"><p class="ordercraft-kicker"><?php esc_html_e( 'One connected workflow', 'iamgsbala' ); ?></p><ol><li><b>01</b><?php esc_html_e( 'Specifications', 'iamgsbala' ); ?></li><li><b>02</b><?php esc_html_e( 'Artwork', 'iamgsbala' ); ?></li><li><b>03</b><?php esc_html_e( 'Proof', 'iamgsbala' ); ?></li><li><b>04</b><?php esc_html_e( 'Approval', 'iamgsbala' ); ?></li><li><b>05</b><?php esc_html_e( 'Production', 'iamgsbala' ); ?></li></ol></div></section>

	<section class="ordercraft-content-section shell"><div class="ordercraft-section-heading"><p class="ordercraft-kicker">01 / <?php esc_html_e( 'Why OrderCraft Studio', 'iamgsbala' ); ?></p><h2><?php esc_html_e( 'Make every custom order easier to understand.', 'iamgsbala' ); ?></h2><p><?php esc_html_e( 'Custom work becomes difficult when the customer brief, uploaded files, approval messages and production hand-off live in different places. OrderCraft Studio connects those moments to the WooCommerce order.', 'iamgsbala' ); ?></p></div><div class="ordercraft-feature-grid"><article><span>01</span><h3><?php esc_html_e( 'Capture the brief', 'iamgsbala' ); ?></h3><p><?php esc_html_e( 'Add structured product specification fields and preserve the submitted values as an immutable snapshot on the Job.', 'iamgsbala' ); ?></p></article><article><span>02</span><h3><?php esc_html_e( 'Protect the files', 'iamgsbala' ); ?></h3><p><?php esc_html_e( 'Receive artwork and proof files through protected storage and authenticated preview or download links.', 'iamgsbala' ); ?></p></article><article><span>03</span><h3><?php esc_html_e( 'Get a clear yes', 'iamgsbala' ); ?></h3><p><?php esc_html_e( 'Give customers a dedicated My Account review area to approve proofs or request changes with context.', 'iamgsbala' ); ?></p></article><article><span>04</span><h3><?php esc_html_e( 'Move work forward', 'iamgsbala' ); ?></h3><p><?php esc_html_e( 'Give staff validated Job transitions, activity history, notes and matching WooCommerce order statuses.', 'iamgsbala' ); ?></p></article></div></section>

	<section class="ordercraft-story-section"><div class="shell ordercraft-story-grid"><div><p class="ordercraft-kicker">02 / <?php esc_html_e( 'The customer journey', 'iamgsbala' ); ?></p><h2><?php esc_html_e( 'Confidence before production.', 'iamgsbala' ); ?></h2><p><?php esc_html_e( 'Customers see what the team is reviewing, which proof is current and what action is needed. They can return to the same Artwork & Proofs area as the order progresses.', 'iamgsbala' ); ?></p><a class="ordercraft-text-link" href="<?php echo esc_url( iamgsbala_ordercraft_url( 'ordercraft-documentation' ) ); ?>"><?php esc_html_e( 'See the full workflow guide', 'iamgsbala' ); ?> ↗</a></div><div class="ordercraft-journey-card"><div><span>01</span><strong><?php esc_html_e( 'Customer orders', 'iamgsbala' ); ?></strong><small><?php esc_html_e( 'Specifications and artwork are attached to the order.', 'iamgsbala' ); ?></small></div><div><span>02</span><strong><?php esc_html_e( 'Team prepares proof', 'iamgsbala' ); ?></strong><small><?php esc_html_e( 'The current version is sent for review.', 'iamgsbala' ); ?></small></div><div><span>03</span><strong><?php esc_html_e( 'Customer approves', 'iamgsbala' ); ?></strong><small><?php esc_html_e( 'The approved proof becomes the production reference.', 'iamgsbala' ); ?></small></div><div><span>04</span><strong><?php esc_html_e( 'Production begins', 'iamgsbala' ); ?></strong><small><?php esc_html_e( 'Staff move the Job through production and completion.', 'iamgsbala' ); ?></small></div></div></div></section>

	<section class="ordercraft-content-section shell"><div class="ordercraft-section-heading"><p class="ordercraft-kicker">03 / <?php esc_html_e( 'Free today, Pro next', 'iamgsbala' ); ?></p><h2><?php esc_html_e( 'Start with the operational essentials.', 'iamgsbala' ); ?></h2><p><?php esc_html_e( 'The free release is designed to be useful on its own. Pro is being prepared for teams that need deeper automation and visibility.', 'iamgsbala' ); ?></p></div><div class="ordercraft-plan-grid"><article class="ordercraft-plan-card ordercraft-plan-card--free"><div class="ordercraft-plan-top"><span class="ordercraft-plan-badge">FREE</span><span><?php esc_html_e( 'Available now', 'iamgsbala' ); ?></span></div><h3><?php esc_html_e( 'A dependable custom-order workflow', 'iamgsbala' ); ?></h3><p><?php esc_html_e( 'Everything needed to collect, review and approve custom order information before production.', 'iamgsbala' ); ?></p><ul><li><?php esc_html_e( 'Product specification fields', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'Artwork uploads and protected previews', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'Versioned proofs and customer approval', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'Jobs, activity, notes and notifications', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'WooCommerce order status synchronization', 'iamgsbala' ); ?></li></ul><a class="ordercraft-button ordercraft-button--primary" href="https://wordpress.org/plugins/ordercraft-studio-for-woocommerce/" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Install free', 'iamgsbala' ); ?> ↗</a></article><article class="ordercraft-plan-card ordercraft-plan-card--pro"><div class="ordercraft-plan-top"><span class="ordercraft-plan-badge">PRO</span><span><?php esc_html_e( 'Coming soon', 'iamgsbala' ); ?></span></div><h3><?php esc_html_e( 'More control for growing teams', 'iamgsbala' ); ?></h3><p><?php esc_html_e( 'Pro will extend the foundation for teams that manage higher volume, multiple operators and more complex hand-offs.', 'iamgsbala' ); ?></p><ul><li><?php esc_html_e( 'Advanced workflow automation', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'Kanban and team assignments', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'Reporting and operational visibility', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'Cloud storage and integrations', 'iamgsbala' ); ?></li><li><?php esc_html_e( 'Expanded production controls', 'iamgsbala' ); ?></li></ul><span class="ordercraft-plan-note"><?php esc_html_e( 'Pro features will be announced when ready.', 'iamgsbala' ); ?></span></article></div></section>

	<section class="ordercraft-doc-cta"><div class="shell"><div><p class="ordercraft-kicker">04 / <?php esc_html_e( 'Documentation', 'iamgsbala' ); ?></p><h2><?php esc_html_e( 'Know what happens next.', 'iamgsbala' ); ?></h2><p><?php esc_html_e( 'Follow the setup guide, understand the customer approval process and learn how Job statuses map to WooCommerce order statuses.', 'iamgsbala' ); ?></p></div><a class="ordercraft-button ordercraft-button--light" href="<?php echo esc_url( iamgsbala_ordercraft_url( 'ordercraft-documentation' ) ); ?>"><?php esc_html_e( 'Open all documentation', 'iamgsbala' ); ?> ↗</a></div></section>
</main>
<?php get_footer( 'ordercraft' ); ?>
