<?php defined( 'ABSPATH' ) || exit; $contact_form = iamgsbala_contact_form(); ?>
<section class="section shell faq-section" id="questions"><div><p class="eyebrow">BEFORE WE START</p><h2>A little clarity<br>goes a long way.</h2></div><div class="faq-list"><details><summary>Can you work with an existing website?</summary><p>Yes. My work includes troubleshooting, custom features, integrations and maintenance on existing WordPress and WooCommerce sites. We can start with the specific problem you need to solve.</p></details><details><summary>Can you build a custom plugin or payment integration?</summary><p>Yes. Custom PHP, WordPress plugins, REST APIs, webhooks and WooCommerce payment workflows are central to my work. Share the required workflow and any relevant API documentation.</p></details><details><summary>What should I include in my enquiry?</summary><p>Tell me what you want to achieve, the platform you use, and any timing constraints. A website URL is helpful. Please do not send passwords, payment details or other sensitive information.</p></details><details><summary>Where can I get help with your free plugins?</summary><p>Use the public support forums for <a href="https://wordpress.org/support/plugin/fileops-monitor/">FileOps Monitor</a> or <a href="https://wordpress.org/support/plugin/storeops-auditor-for-woocommerce/">StoreOps Auditor</a>. For a custom implementation, use the enquiry form below.</p></details></div></section>
<section id="contact" class="contact-section"><div class="shell contact-inner"><div class="contact-copy"><p class="eyebrow">LET’S TALK ABOUT YOUR PROJECT</p><h2>Good ideas.<br>Thoughtful builds<span>.</span></h2><p>A custom website, a complex integration or a store that needs a fresh perspective. Tell me what you have in mind.</p>
<?php $booking = get_theme_mod( 'iamgsbala_contact_url', '' ); if ( $booking ) : ?><p><a href="<?php echo esc_url( $booking ); ?>">Book a conversation ↗</a></p><?php endif; ?>
<?php $linkedin = get_theme_mod( 'iamgsbala_linkedin', '' ); if ( $linkedin ) : ?><p><a href="<?php echo esc_url( $linkedin ); ?>">Connect on LinkedIn ↗</a></p><?php endif; ?>
<div class="contact-expectations"><span><?php echo iamgsbala_icon( 'check' ); ?> Your goals and existing setup</span><span><?php echo iamgsbala_icon( 'check' ); ?> Clear scope before development</span><span><?php echo iamgsbala_icon( 'check' ); ?> Staging, testing and considered handover</span></div></div>
<div class="contact-panel"><h3>Tell me about your project</h3><p class="form-intro">Fields marked * are required.</p><?php if ( $contact_form ) : ?>
<?php echo do_shortcode( $contact_form->shortcode() ); ?>
<?php else : ?><p>Send your project details to the email address alongside this section.</p><?php if ( current_user_can( 'edit_theme_options' ) ) : ?><p class="form-setup"><a href="<?php echo esc_url( admin_url( 'customize.php' ) ); ?>">Select a Contact Form 7 form in Customize → iamgsbala Profile.</a></p><?php endif; endif; ?>
</div></div></section>
